import Head from "next/head";
import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/router";
import Layout from "../components/Layout";
import Disclaimer from "../components/Disclaimer";

export default function DoctorReportPage() {
  const router = useRouter();
  const [active, setActive] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Form State
  const [patientName, setPatientName] = useState("");
  const [patientAge, setPatientAge] = useState("");
  const [selectedIds, setSelectedIds] = useState(new Set());

  const [notes, setNotes] = useState("");

  // Report State
  const [reportData, setReportData] = useState(null);
  const [generating, setGenerating] = useState(false);
  const reportRef = useRef(null);

  useEffect(() => {
    fetchMedicines();
  }, []);

  const fetchMedicines = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/user-medicines");
      const data = await res.json();
      const activeMeds = data.active || [];
      setActive(activeMeds);
      // Pre-select all by default
      setSelectedIds(new Set(activeMeds.map(m => m._id)));
    } catch {
      setError("Failed to load your medicines.");
    } finally {
      setLoading(false);
    }
  };

  const toggleSelect = (id) => {
    const next = new Set(selectedIds);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setSelectedIds(next);
  };

  const handleGenerate = async () => {
    try {
      const selectedMeds = active.filter(m => selectedIds.has(m._id));
      if (selectedMeds.length === 0) {
        alert("Please select at least one medicine to include in the report.");
        return;
      }

      setGenerating(true);
      setReportData({
        patient: { name: patientName, age: patientAge, notes },
        medicines: selectedMeds,
        date: new Date().toLocaleDateString("en-IN", {
          year: "numeric", month: "long", day: "numeric"
        })
      });
    } catch {
      alert("Failed to generate report details. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const exportPdf = async () => {
    if (!reportRef.current || typeof window === "undefined") return;
    try {
      const html2pdf = (await import("html2pdf.js")).default;
      const element = reportRef.current;
      const options = {
        margin: [10, 10, 10, 10], // top left bottom right
        filename: `MediSimple_Doctor_Report_${new Date().toISOString().split('T')[0]}.pdf`,
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { orientation: "portrait", unit: "mm", format: "a4" },
      };
      html2pdf().set(options).from(element).save();
    } catch {
      window.print();
    }
  };

  const exportEmail = () => {
    if (!reportData) return;
    let body = `MediSimple Medicine Report\nDate: ${reportData.date}\n\n`;
    if (reportData.patient.name) body += `Patient: ${reportData.patient.name}\n`;
    if (reportData.patient.age) body += `Age: ${reportData.patient.age}\n`;

    body += `\n=== CURRENT MEDICINES (${reportData.medicines.length}) ===\n`;
    reportData.medicines.forEach((m, i) => {
      body += `${i + 1}. ${m.name} ${m.strength} (Since: ${new Date(m.startDate).toLocaleDateString()})\n`;
      if (m.frequency) body += `   ${m.frequency}\n`;
    });

    if (reportData.patient.notes) {
      body += `\n=== PATIENT NOTES ===\n${reportData.patient.notes}\n`;
    }

    body += `\nDisclaimer: This report is generated by an AI app for educational purposes. It is NOT a medical diagnosis or treatment recommendation. Always consult your doctor for medical decisions.`;

    window.location.href = `mailto:?subject=Medicine Report for ${reportData.patient.name || "Patient"}&body=${encodeURIComponent(body)}`;
  };

  return (
    <Layout title="Doctor Report">
      <Head>
        <title>Generate Doctor Report — MediSimple</title>
        <meta name="description" content="Export your medicine list to share with your doctor." />
      </Head>

      <div className="page-content">
        <div className="fade-in" style={{ marginBottom: 24 }}>
          <h1
            style={{
              fontFamily: "Poppins, sans-serif",
              fontWeight: 800,
              fontSize: 24,
              color: "var(--text-primary)",
              marginBottom: 6,
            }}
          >
            📋 Generate Report for Your Doctor
          </h1>
          <p style={{ color: "var(--text-secondary)", fontSize: 15 }}>
            Create a clear, printable summary of your medicines to share at your next appointment.
          </p>
        </div>

        {!reportData ? (
          /* CONFIGURATION FORM */
          <div className="card fade-in-up" style={{ marginBottom: 24 }}>
            <div className="grid-2" style={{ gap: 16, marginBottom: 16 }}>
              <div className="input-group" style={{ marginBottom: 0 }}>
                <label className="input-label">Patient Name (Optional)</label>
                <input
                  type="text"
                  className="input"
                  value={patientName}
                  onChange={(e) => setPatientName(e.target.value)}
                  placeholder="e.g., Ramesh K."
                />
              </div>
              <div className="input-group" style={{ marginBottom: 0 }}>
                <label className="input-label">Age (Optional)</label>
                <input
                  type="text"
                  className="input"
                  value={patientAge}
                  onChange={(e) => setPatientAge(e.target.value)}
                  placeholder="e.g., 54"
                />
              </div>
            </div>

            <div style={{ marginBottom: 20 }}>
              <h3 style={{ fontFamily: "Poppins, sans-serif", fontWeight: 700, fontSize: 15, marginBottom: 12 }}>
                Select Medicines to Include:
              </h3>

              {loading ? (
                <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>Loading medicines...</p>
              ) : error ? (
                <p style={{ fontSize: 14, color: "var(--danger)" }}>{error}</p>
              ) : active.length === 0 ? (
                <p style={{ fontSize: 14, color: "var(--text-secondary)", padding: "12px", background: "var(--gray-50)", borderRadius: 8 }}>
                  No active medicines found. Please add medicines in the <a href="/my-medicines">My Meds</a> tab first.
                </p>
              ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  {active.map(m => (
                    <label key={m._id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "10px 12px", border: "1px solid var(--gray-200)", borderRadius: 8, cursor: "pointer", background: selectedIds.has(m._id) ? "var(--primary-light)" : "white" }}>
                      <input
                        type="checkbox"
                        checked={selectedIds.has(m._id)}
                        onChange={() => toggleSelect(m._id)}
                        style={{ width: 18, height: 18, accentColor: "var(--primary)" }}
                      />
                      <span style={{ fontWeight: 600, color: "var(--text-primary)" }}>{m.name} {m.strength}</span>
                    </label>
                  ))}
                </div>
              )}
            </div>



            <div className="input-group">
              <label className="input-label">Notes for Doctor (Optional)</label>
              <textarea
                className="input"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="e.g., Having slight nausea in the mornings..."
                rows={3}
                style={{ resize: "vertical" }}
              />
            </div>

            <button
              className="btn btn-primary btn-full btn-lg"
              style={{ marginTop: 8 }}
              onClick={handleGenerate}
              disabled={generating || selectedIds.size === 0}
            >
              {generating ? "Generating..." : "📋 Generate Report Preview"}
            </button>
          </div>
        ) : (
          /* REPORT PREVIEW & EXPORT ACTIONS */
          <div className="fade-in-up">
            <div className="grid-2" style={{ marginBottom: 20 }}>
              <button className="btn btn-primary" onClick={exportPdf}>🖨️ Export as PDF / Print</button>
              <button className="btn btn-secondary" onClick={exportEmail}>✉️ Email Report</button>
            </div>

            <button className="btn btn-ghost btn-sm" style={{ marginBottom: 16 }} onClick={() => setReportData(null)}>
              ← Edit Configuration
            </button>

            {/* ACTUAL REPORT DOM FOR PDF EXPORT */}
            <div
              ref={reportRef}
              className="card"
              style={{
                background: "white",
                padding: "32px 40px",
                border: "1px solid var(--gray-300)",
                boxShadow: "var(--shadow-md)"
              }}
            >
              <div style={{ borderBottom: "3px solid var(--primary)", paddingBottom: 16, marginBottom: 24, display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
                <div>
                  <h1 style={{ fontFamily: "Poppins, sans-serif", fontWeight: 800, fontSize: 28, color: "var(--primary-darker)", margin: 0 }}>
                    Patient Medicine Report
                  </h1>
                  <p style={{ fontSize: 16, color: "var(--text-secondary)", margin: "4px 0 0" }}>MediSimple App Export</p>
                </div>
                <div style={{ textAlign: "right" }}>
                  <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text-primary)" }}>Date: {reportData.date}</div>
                </div>
              </div>

              {/* Patient Info */}
              {(reportData.patient.name || reportData.patient.age) && (
                <div style={{ marginBottom: 24 }}>
                  <h3 style={{ fontSize: 12, fontWeight: 700, letterSpacing: 1, color: "var(--gray-500)", marginBottom: 8, textTransform: "uppercase" }}>
                    Patient Information
                  </h3>
                  <div style={{ background: "var(--gray-50)", padding: 12, borderRadius: 8, display: "flex", gap: 32 }}>
                    {reportData.patient.name && (
                      <div><span style={{ color: "var(--text-secondary)", fontSize: 13 }}>Name:</span> <strong style={{ fontSize: 15 }}>{reportData.patient.name}</strong></div>
                    )}
                    {reportData.patient.age && (
                      <div><span style={{ color: "var(--text-secondary)", fontSize: 13 }}>Age:</span> <strong style={{ fontSize: 15 }}>{reportData.patient.age}</strong></div>
                    )}
                  </div>
                </div>
              )}

              {/* Medicines List */}
              <div style={{ marginBottom: 24 }}>
                <h3 style={{ fontSize: 12, fontWeight: 700, letterSpacing: 1, color: "var(--primary)", marginBottom: 12, textTransform: "uppercase", borderBottom: "1px solid var(--gray-200)", paddingBottom: 6 }}>
                  Current Medications ({reportData.medicines.length})
                </h3>
                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
                  <thead>
                    <tr style={{ background: "var(--gray-50)", borderBottom: "2px solid var(--gray-200)" }}>
                      <th style={{ padding: "10px", textAlign: "left", color: "var(--gray-600)" }}>Medicine</th>
                      <th style={{ padding: "10px", textAlign: "left", color: "var(--gray-600)" }}>Frequency / Directions</th>
                      <th style={{ padding: "10px", textAlign: "left", color: "var(--gray-600)" }}>Since</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.medicines.map((m, i) => (
                      <tr key={i} style={{ borderBottom: "1px solid var(--gray-200)" }}>
                        <td style={{ padding: "12px 10px", fontWeight: 600 }}>{m.name} {m.strength}</td>
                        <td style={{ padding: "12px 10px", color: "var(--gray-700)" }}>{m.frequency || "Not specified"}</td>
                        <td style={{ padding: "12px 10px", color: "var(--gray-500)", fontSize: 13 }}>{new Date(m.startDate).toLocaleDateString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>



              {/* Notes */}
              {reportData.patient.notes && (
                <div style={{ marginBottom: 32 }}>
                  <h3 style={{ fontSize: 12, fontWeight: 700, letterSpacing: 1, color: "var(--primary)", marginBottom: 12, textTransform: "uppercase", borderBottom: "1px solid var(--gray-200)", paddingBottom: 6 }}>
                    Patient Notes / Symptoms
                  </h3>
                  <p style={{ fontSize: 14, lineHeight: 1.6, padding: 12, background: "var(--warning-light)", border: "1px solid var(--warning-border)", borderRadius: 8, whiteSpace: "pre-wrap", margin: 0 }}>
                    {reportData.patient.notes}
                  </p>
                </div>
              )}

              {/* CRITICAL VERBATIM DISCLAIMER */}
              <div style={{
                background: "#F3F4F6",
                padding: 16,
                borderRadius: 8,
                fontSize: 12,
                color: "#4B5563",
                borderLeft: "4px solid #9CA3AF",
                lineHeight: 1.5,
                marginTop: 40
              }}>
                <strong>Disclaimer:</strong> This report is generated by an AI app for educational purposes.
                It is NOT a medical diagnosis or treatment recommendation.
                Always consult your doctor for medical decisions.
              </div>
            </div>
          </div>
        )}
        <div style={{ height: 40 }} />
      </div>
    </Layout>
  );
}
